# 自动交易机器人配置文件
# Auto Trading Bot Configuration

# 交易设置
TRADING = {
    "enabled": True,
    "max_position_size": 1000,  # 最大持仓金额 (USDT)
    "min_trade_amount": 10,     # 最小交易金额 (USDT)
    "profit_target": 0.05,      # 目标盈利 5%
    "stop_loss": 0.05,          # 止损 5%
    "trading_frequency": 300,   # 交易频率 (秒)
    "max_daily_trades": 50,     # 每日最大交易次数
}

# 交易所配置
EXCHANGES = {
    "binance": {
        "enabled": True,
        "api_key": "",
        "api_secret": "",
        "sandbox": True,  # 测试环境
        "rate_limit": 1200,  # 每分钟请求限制
    },
    "okx": {
        "enabled": False,
        "api_key": "",
        "api_secret": "",
        "passphrase": "",
        "sandbox": True,
    }
}

# 算法配置
ALGORITHM = {
    "strategy": "rsi_macd",  # 策略类型: rsi_macd, bollinger, moving_average
    "rsi_period": 14,
    "rsi_oversold": 30,
    "rsi_overbought": 70,
    "macd_fast": 12,
    "macd_slow": 26,
    "macd_signal": 9,
    "bollinger_period": 20,
    "bollinger_std": 2,
    "ma_short": 10,
    "ma_long": 30,
}

# 交易对配置
SYMBOLS = [
    "BTC/USDT",
    "ETH/USDT",
    "BNB/USDT",
]

# 日志配置
LOGGING = {
    "level": "INFO",
    "file": "logs/trading_bot.log",
    "max_size": "10MB",
    "backup_count": 5,
}

# 风险控制
RISK_MANAGEMENT = {
    "max_drawdown": 0.1,      # 最大回撤 10%
    "max_concurrent_positions": 3,  # 最大同时持仓数
    "position_size_percent": 0.1,   # 每次交易占总资金比例
    "emergency_stop_loss": 0.15,    # 紧急止损 15%
}
